# Generated by Django 5.1.7 on 2025-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
            ],
        ),
    ]
