# Generated by Django 5.1.7 on 2025-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
