# Generated by Django 5.1.7 on 2025-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_gendercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='detecteduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detected_users/'),
        ),
    ]
