# Generated by Django 5.1.7 on 2025-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_detecteduser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
