# Generated by Django 5.1.7 on 2025-04-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0004_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detecteduser',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='detecteduser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gendercount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, unique=True),
        ),
    ]
