# Generated by Django 5.1.7 on 2025-04-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0005_alter_detecteduser_options_alter_detecteduser_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detecteduser',
            options={},
        ),
        migrations.RemoveField(
            model_name='detecteduser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='detecteduser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
